proyecto/clinica/urls.py
from django.urls import path
from . import views

app_name = 'clinica'

urlpatterns = [
    path('', views.home, name='home'),
    path('paciente/create', views.PacienteCreateView.as_view(), name='paciente-create'),
    path('paciente', views.PacienteListView.as_view(), name='paciente-list'),
    path('paciente/editar/<int:pk>', views.PacienteUpdateView.as_view(), name='paciente-update'),
    path('paciente/eliminar/<int:pk>', views.PacienteDeleteView.as_view(), name='paciente-delete'),

    path('medico/create', views.MedicoCreateView.as_view(), name='medico-create'),
    path('medico', views.MedicoListView.as_view(), name='medico-list'),
    path('medico/editar/<int:pk>', views.MedicoUpdateView.as_view(), name='medico-update'),
    path('medico/eliminar/<int:pk>', views.MedicoDeleteView.as_view(), name='medico-delete'),

    path('historia', views.historia_view, name='historia'),
    path('contacto', views.contacto_view, name='contacto'),
    path('formularios', views.formulario_view, name='formulario'),

    path('crear_cita/<int:paciente_id>/', views.CitaCreateView.as_view(), name='cita-create'),
    path('cita/editar/<int:pk>/', views.CitaUpdateView.as_view(), name='cita-edit'),
    path('cita/', views.CitaListView.as_view(), name='cita-list'),
    path('cita/<int:pk>/', views.CitaDetailView.as_view(), name='cita-detail'),
    path('paciente/<int:pk>/citas/', views.CitasPacienteView.as_view(), name='citas-paciente'),
    path('cita/<int:pk>/delete/', views.CitaDeleteView.as_view(), name='cita-delete'),
]

proyecto/proyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clinica.urls', namespace='clinica')),
    path('cuenta/', include('usuario.urls', namespace='usuario')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

proyecto/clinica/models.py
from django.db import models

class Medico(models.Model):
    nombre = models.CharField(max_length=128)
    numero_colegiado = models.CharField(max_length=64)
    especialidad = models.CharField(max_length=64)

    def __str__(self):
        return self.nombre

class Paciente(models.Model):
    nombre = models.CharField(max_length=128)
    dpi = models.CharField(max_length=64)
    fecha_de_nacimiento = models.DateField()
    direccion = models.CharField(max_length=128)
    numero_telefonico = models.CharField(max_length=64)

    def __str__(self):
        return self.nombre

class Cita(models.Model):
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    fecha_cita = models.DateTimeField()
    diagnostico = models.CharField(max_length=128, blank=True, null=True)
    receta_medica = models.CharField(max_length=128, blank=True, null=True)
    razon_de_visita = models.CharField(max_length=128, blank=True, null=True)
    cita_hecha = models.BooleanField(default=False)

    def estado_cita(self):
        return 'Realizado' if self.cita_hecha else 'No Realizado'

    def __str__(self):
        return f"---Médico: {self.medico.nombre} - {self.fecha_cita} - Diagnóstico: {self.diagnostico} - Receta Médica: {self.receta_medica} - Razón de Visita: {self.razon_de_visita} - Entregado: {self.estado_cita()}"

proyecto/clinica/forms.py
from django import forms
from .models import Paciente, Medico

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente

        fields = [
            'nombre',
            'dpi',
            'fecha_de_nacimiento',
            'direccion',
            'numero_telefonico',
        ]

        labels = {
            'nombre': 'Nombre completo',
            'dpi': 'Número de DPI',
            'fecha_de_nacimiento': 'Fecha de nacimiento',
            'direccion': 'Dirección',
            'numero_telefonico': 'Número telefónico',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su nombre'}),
            'dpi': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su número de DPI'}),
            'fecha_de_nacimiento': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su dirección residencial'}),
            'numero_telefonico': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su número telefónico'}),
        }


class MedicoForm(forms.ModelForm):
    class Meta:
        model = Medico

        fields = [
            'nombre',
            'numero_colegiado',
            'especialidad',
        ]

        labels = {
            'nombre': 'Nombre completo',
            'numero_colegiado': 'Número de colegiado',
            'especialidad': 'Especialidad',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su nombre'}),
            'numero_colegiado': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su número de colegiado'}),
            'especialidad': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su especialidad'}),
        }

from django import forms
from .models import Cita

from django import forms
from .models import Cita

class CitaForm(forms.ModelForm):
    class Meta:
        model = Cita

        fields = [
            'medico',
            'fecha_cita',
            'razon_de_visita',
            'diagnostico',
            'receta_medica',
            'cita_hecha',
        ]

        labels = {
            'medico': 'Médico',
            'fecha_cita': 'Fecha de la cita',
            'razon_de_visita': 'Razón de Visita',
            'diagnostico': 'Diagnóstico',
            'receta_medica': 'Receta Médica',
            'cita_hecha': 'Cita Finalizada',
        }

        widgets = {
            'medico': forms.Select(attrs={'class': 'form-control'}),
            'fecha_cita': forms.DateInput(attrs={'type': 'date', 'class': 'form-control',}),
            'razon_de_visita': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese la razón de la visita'}),
            'diagnostico': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el diagnóstico'}),
            'receta_medica': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese la receta médica'}),
            'cita_hecha': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'paciente': forms.HiddenInput(),
        }

proyecto/clinica/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Paciente, Medico, Cita
from .forms import PacienteForm, MedicoForm, CitaForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

def home(request):
    return render(request, 'clinica/home.html')


class PacienteListView(ListView):
    model = Paciente
    template_name = 'clinica/paciente/paciente_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pacientes = Paciente.objects.all()
        citas_por_paciente = {}

        for paciente in pacientes:
            citas_no_hechas = Cita.objects.filter(paciente=paciente, cita_hecha=False)
            citas_por_paciente[paciente] = citas_no_hechas
        
        print(citas_por_paciente)

        context['citas_por_paciente'] = citas_por_paciente
        return context

@method_decorator(login_required, name='dispatch')
class PacienteCreateView(CreateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'clinica/paciente/paciente_form.html'
    success_url = reverse_lazy('clinica:paciente-list')

@method_decorator(login_required, name='dispatch')
class PacienteUpdateView(UpdateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'clinica/paciente/paciente_update.html'
    success_url = reverse_lazy('clinica:paciente-list')

@method_decorator(login_required, name='dispatch')
class PacienteDeleteView(DeleteView):
    model = Paciente
    template_name = 'clinica/paciente/paciente_delete.html'
    success_url = reverse_lazy('clinica:paciente-list')

class MedicoListView(ListView):
    model = Medico
    template_name = 'clinica/medico/medico_list.html'

@method_decorator(login_required, name='dispatch')
class MedicoCreateView(CreateView):
    model = Medico
    form_class = MedicoForm
    template_name = 'clinica/medico/medico_form.html'
    success_url = reverse_lazy('clinica:medico-list')

@method_decorator(login_required, name='dispatch')
class MedicoUpdateView(UpdateView):
    model = Medico
    form_class = MedicoForm
    template_name = 'clinica/medico/medico_update.html'
    success_url = reverse_lazy('clinica:medico-list')

@method_decorator(login_required, name='dispatch')
class MedicoDeleteView(DeleteView):
    model = Medico
    template_name = 'clinica/medico/medico_delete.html'
    success_url = reverse_lazy('clinica:medico-list')

def historia_view(request):
    return render(request, 'clinica/web/historia.html')

def contacto_view(request):
    return render(request, 'clinica/web/contacto.html')

def formulario_view(request):
    return render(request, 'clinica/web/formulario.html')


class CitaCreateView(CreateView):
    model = Cita
    form_class = CitaForm
    template_name = 'clinica/cita/cita_form.html'
    success_url = reverse_lazy('clinica:paciente-list')

    def form_valid(self, form):
        # Obtén el paciente que se pasa como parámetro en la URL
        paciente_id = self.kwargs['paciente_id']
        paciente = get_object_or_404(Paciente, pk=paciente_id)

        # Asigna el paciente al formulario antes de guardarlo
        form.instance.paciente = paciente

        # Llama al método form_valid de la clase base para continuar con el proceso de guardado
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class CitaUpdateView(UpdateView):
    model = Cita
    form_class = CitaForm
    template_name = 'clinica/cita/cita_form.html'

    def get_success_url(self):
        paciente_id = self.object.paciente.id
        return reverse_lazy('clinica:citas-paciente', kwargs={'pk': paciente_id})

class CitaListView(ListView):
    model = Cita
    template_name = 'cita_list.html'

class CitaDetailView(DetailView):
    model = Cita
    template_name = 'cita_detail.html'

class CitasPacienteView(DetailView):
    model = Paciente
    template_name = 'clinica/cita/paciente/citas_paciente.html'
    context_object_name = 'paciente'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paciente = self.object
        citas_paciente = paciente.cita_set.all()
        context['paciente'] = paciente
        context['citas_paciente'] = citas_paciente
        return context

@method_decorator(login_required, name='dispatch')
class CitaDeleteView(DeleteView):
    model = Cita
    template_name = 'clinica/cita/paciente/cita_confirm_delete.html'
    success_url = reverse_lazy('clinica:paciente-list')

proyecto/templates/clinica/medico/medico_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
        <form method="post">
            {% csrf_token %}
            <h3>¿Desea eliminar al médico {{object.nombre}}?</h3>
            <div class="content">
                <button class="btn btn-danger" type="submit">Si, eliminar</button>
                <a class="btn btn-default" href="{% url 'clinica:medico-list' %}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content %}

proyecto/templates/clinica/medico/medico_form.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h4 style="text-align: center;">Agregar nuevo médico</h4>
        <div class="btn-container">
            <a class="btn btn-medic" href="{% url 'clinica:medico-list' %}">Cancelar</a>
        </div>
        <form method="post" class="form">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-item">
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endfor %}
            <div class="btn-container">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>
    </div>
{% endblock content %}

proyecto/templates/clinica/medico/medico_list.html
{% extends 'base.html' %}

{% block content %}
<div class="tabla-registro">

    <div class="container-btn">
        <a class="btn btn-medic" href="{% url 'clinica:medico-create' %}">Ingresar nuevo médico</a>
        <a class="btn btn-medic" href="{% url 'clinica:paciente-list' %}">Pacientes</a>
    </div>

    <div>
        <table class="table table-striped">
            <thead class="text-center align-middle">
                <tr>
                    <td>Nombre</td>
                    <td>Número de colegiado</td>
                    <td>Especialidad</td>
                    <td>Opciones</td>
                </tr>
            </thead>
            <tbody class="text-center align-middle">
                {% if object_list %}
                {% for medico in object_list %}
                <tr>
                    <td>{{medico.nombre}}</td>
                    <td>{{medico.numero_colegiado}}</td>
                    <td>{{medico.especialidad}}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'clinica:medico-update' medico.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'clinica:medico-delete' medico.id %}">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="5" class="text-center">No hay registros</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

</div>


{% endblock content %}

proyecto/templates/clinica/medico/medico_update.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h4 style="text-align: center;">Editar al médico {{ object.nombre }}</h4>
        <div class="btn-container">
            <a class="btn btn-medic" href="{% url 'clinica:medico-list' %}">Cancelar</a>
        </div>
        <form method="post" class="form">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-item">
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endfor %}
            <div class="btn-container">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>
    </div>
{% endblock content %}