proyecto/clinica/urls.py
from django.urls import path
from . import views

app_name = 'clinica'

urlpatterns = [
    path('', views.home, name='home'),
    path('paciente/create', views.PacienteCreateView.as_view(), name='paciente-create'),
    path('paciente', views.PacienteListView.as_view(), name='paciente-list'),
    path('paciente/editar/<int:pk>', views.PacienteUpdateView.as_view(), name='paciente-update'),
    path('paciente/eliminar/<int:pk>', views.PacienteDeleteView.as_view(), name='paciente-delete'),

    path('medico/create', views.MedicoCreateView.as_view(), name='medico-create'),
    path('medico', views.MedicoListView.as_view(), name='medico-list'),
    path('medico/editar/<int:pk>', views.MedicoUpdateView.as_view(), name='medico-update'),
    path('medico/eliminar/<int:pk>', views.MedicoDeleteView.as_view(), name='medico-delete'),

    path('historia', views.historia_view, name='historia'),
    path('contacto', views.contacto_view, name='contacto'),
    path('formularios', views.formulario_view, name='formulario'),

    path('crear_cita/<int:paciente_id>/', views.CitaCreateView.as_view(), name='cita-create'),
    path('cita/editar/<int:pk>/', views.CitaUpdateView.as_view(), name='cita-edit'),
    path('cita/', views.CitaListView.as_view(), name='cita-list'),
    path('cita/<int:pk>/', views.CitaDetailView.as_view(), name='cita-detail'),
    path('paciente/<int:pk>/citas/', views.CitasPacienteView.as_view(), name='citas-paciente'),
    path('cita/<int:pk>/delete/', views.CitaDeleteView.as_view(), name='cita-delete'),
]

proyecto/proyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clinica.urls', namespace='clinica')),
    path('cuenta/', include('usuario.urls', namespace='usuario')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

proyecto/templates/clinica/cita/paciente/cita_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
        <form method="post">
            {% csrf_token %}
            <h3>¿Desea eliminar la cita de {{object.paciente}}?</h3>
            <div class="content">
                <button class="btn btn-danger" type="submit">Si, eliminar</button>
                <a class="btn btn-default" href="{% url 'clinica:medico-list' %}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content %}

proyecto/templates/clinica/cita/paciente/citas_paciente.html
{% extends 'base.html' %}

{% block content %}
  <h1>Citas de {{ paciente.nombre }}</h1>

  <h2>Información del Paciente</h2>
  <p>Nombre: {{ paciente.nombre }}</p>
  <p>DPI: {{ paciente.dpi }}</p>
  <p>Fecha de Nacimiento: {{ paciente.fecha_de_nacimiento }}</p>
  
  <h2>Citas Pendientes</h2>
  {% if citas_paciente %}
    <ul>
      {% for cita in citas_paciente %}
        {% if not cita.cita_hecha %}
          <div style="display: flex;">
            <div>
              <li class="list-group-item list-group-item-primary">{{ cita }}</li>
            </div>
            <div>
              <div class="container-btns">
                <a class="btn btn-primary" href="{% url 'clinica:cita-edit' cita.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'clinica:cita-delete' cita.id %}">Eliminar</a>
              </div>
            </div>
          </div>
          <br>
          {% else %}
          No hay registro
        {% endif %}
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay citas pendientes para este paciente.</p>
  {% endif %}

  <br>
  <br>


  <h2>Citas Realizadas</h2>
  {% if citas_paciente %}
    <ul>
      {% for cita in citas_paciente %}
        {% if cita.cita_hecha %}
          <div style="display: flex;">
            <div>
              <li class="list-group-item list-group-item-success">{{ cita }}</li>
            </div>
            <div>
              <div class="container-btns">
                <a class="btn btn-primary" href="{% url 'clinica:cita-edit' cita.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'clinica:cita-delete' cita.id %}">Eliminar</a>
              </div>
            </div>
          </div>
          <br>
          {% else %}
          No hay registro
        {% endif %}
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay citas realizadas para este paciente.</p>
  {% endif %}

    <br>
    <br>
    <br>
  <a href="{% url 'clinica:paciente-list' %}">Volver a la lista de pacientes</a>
{% endblock %}