proyecto/clinica/urls.py
from django.urls import path
from . import views

app_name = 'clinica'

urlpatterns = [
    path('', views.home, name='home'),
    path('paciente/create', views.PacienteCreateView.as_view(), name='paciente-create'),
    path('paciente', views.PacienteListView.as_view(), name='paciente-list'),
    path('paciente/editar/<int:pk>', views.PacienteUpdateView.as_view(), name='paciente-update'),
    path('paciente/eliminar/<int:pk>', views.PacienteDeleteView.as_view(), name='paciente-delete'),

    path('medico/create', views.MedicoCreateView.as_view(), name='medico-create'),
    path('medico', views.MedicoListView.as_view(), name='medico-list'),
    path('medico/editar/<int:pk>', views.MedicoUpdateView.as_view(), name='medico-update'),
    path('medico/eliminar/<int:pk>', views.MedicoDeleteView.as_view(), name='medico-delete'),

    path('historia', views.historia_view, name='historia'),
    path('contacto', views.contacto_view, name='contacto'),
    path('formularios', views.formulario_view, name='formulario'),

    path('crear_cita/<int:paciente_id>/', views.CitaCreateView.as_view(), name='cita-create'),
    path('cita/editar/<int:pk>/', views.CitaUpdateView.as_view(), name='cita-edit'),
    path('cita/', views.CitaListView.as_view(), name='cita-list'),
    path('cita/<int:pk>/', views.CitaDetailView.as_view(), name='cita-detail'),
    path('paciente/<int:pk>/citas/', views.CitasPacienteView.as_view(), name='citas-paciente'),
    path('cita/<int:pk>/delete/', views.CitaDeleteView.as_view(), name='cita-delete'),
]

proyecto/proyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clinica.urls', namespace='clinica')),
    path('cuenta/', include('usuario.urls', namespace='usuario')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

proyecto/usuario/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'usuario'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
]

proyecto/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Clinica Médica{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="icon" type="img/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    {% block stylesheet %}{% endblock stylesheet %}
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="container-navbar">
                <div class="navbar-left">
                    <div>
                        <a class="navbar-left_icon" href="{% url 'clinica:home' %}"><img style="height: 32px;" src="{% static 'img/heart-beat.png' %}" alt="img"></a>
                
                        <div class="ham-menu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>
                </div>
                <div class="navbar-mid">
                    <div class="navbar-menu">
                        <ul class="navbar-items">
                            <li class="navbar-item"><a href="{% url 'clinica:home' %}">Inicio</a></li>
                            <li class="navbar-item"><a href="{% url 'clinica:formulario' %}">Formulario</a></li>
                            <li class="navbar-item"><a href="{% url 'clinica:contacto' %}">Contacto</a></li>
                            <li class="navbar-item"><a href="{% url 'clinica:historia' %}">Historia</a></li>
                        </ul>
                    </div>
                </div>
                <div class="navbar-right">
                    <a href="{% url 'usuario:login' %}"><img style="height: 32px;" src="{% static 'img/user.png' %}" alt="img"></a>
                    {% if user.is_authenticated %}
                    <div class="navbar__user-name">
                        <a class="dropdown-toggle" id="dropdown-toggle">{{ request.user.name}}</a>
                        <ul class="dropdown-menu" id="dropdown-menu">
                            <li><a href="{% url 'usuario:logout' %}" class="dropdown-item">Cerrar Sesion</a></li>

                        </ul>
                        </div>
                        {% else %}
                        <div class="navbar__user-name dropdown">
                        <a href="{% url 'usuario:login' %}">Login</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>   

        <!-- navbar modal -->
        <nav class="navbar-modal__menu">
            <ul class="navbar-modal__items">
                
                <li class="navbar-modal__item"><a href="{% url 'clinica:home' %}">Inicio</a></li>
                <li class="navbar-item"><a href="{% url 'clinica:formulario' %}">Formulario</a></li>
                <li class="navbar-modal__item"><a href="{% url 'clinica:contacto' %}">Contacto</a></li>
                <li class="navbar-modal__item"><a href="{% url 'clinica:historia' %}">Historia</a></li>
            </ul>
        </nav>
        <div class="navbar-modal__background"></div>
        <!-- navbar modal -->


    <main class="container">
        {% block content %}{% endblock content %}
    </main>

    <footer class="footer">
        &copy; Copyright 2023 - Clínica Médica La Eterna Primavera
    </footer>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js"></script>
    {% block javascrip %}{% endblock javascrip %}
</body>
</html>